# Generated by Django 4.1.7 on 2023-08-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('dth_sensor', models.BooleanField()),
                ('type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=15)),
                ('pin_number', models.IntegerField()),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
            ],
        ),
    ]
