# Generated by Django 4.1.7 on 2023-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=15)),
                ('pin_number', models.IntegerField()),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
            ],
        ),
    ]
