# Generated by Django 4.1.7 on 2023-07-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('sensor_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('description', models.TextField()),
                ('served', models.BooleanField()),
                ('alert_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
